/*create user schema student_examination_sys*/
create user student_examination_sys identified by Pass1234;
grant connect to student_examination_sys;
grant connect, resource, dba to student_examination_sys;
GRANT CREATE SESSION to student_examination_sys;
GRANT UNLIMITED TABLESPACE TO student_examination_sys;

/*create user_table under STUDENT_EXAMINATION_SYS schema*/
create table STUDENT_EXAMINATION_SYS.user_table(table_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
table_name VARCHAR2(50) NOT NULL,
PRIMARY KEY(table_id));

/* insert table name into user_table */
insert into STUDENT_EXAMINATION_SYS.user_table(table_name) values ('student');
insert into STUDENT_EXAMINATION_SYS.user_table(table_name) values ('subject');
insert into STUDENT_EXAMINATION_SYS.user_table(table_name) values('score');

/*create table student*/
create table STUDENT_EXAMINATION_SYS.STUDENT(student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
student_name VARCHAR2(50) NOT NULL,
age NUMBER NOT NULL,
sex VARCHAR2(50) NOT NULL,
PRIMARY KEY (student_id));

/*create table subject*/
create table STUDENT_EXAMINATION_SYS.SUBJECT(subject_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
subject VARCHAR2(50) NOT NULL,
teacher VARCHAR2(50) NOT NULL,
description VARCHAR2(100) NOT NULL,
PRIMARY KEY (subject_id));

/*create table score*/
create table STUDENT_EXAMINATION_SYS.SCORE(score_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
student_id INT NOT NULL,
subject_id INT NOT NULL,
score FLOAT NOT NULL,
PRIMARY KEY (score_id));

/*Insert two student record into student table*/
INSERT INTO STUDENT_EXAMINATION_SYS.student(student_id, student_name, age, sex) VALUES ('001','zhangsan','18','male');

INSERT INTO STUDENT_EXAMINATION_SYS.student(student_id, student_name, age, sex) VALUES ('002','lisi',20,'female');

/*Insert two subject record into subject table*/
INSERT INTO STUDENT_EXAMINATION_SYS.subject(subject_id,subject,teacher,description) VALUES ('1001','Chinese','Mr. Wang','the exam is easy');
INSERT INTO STUDENT_EXAMINATION_SYS.subject(subject_id,subject,teacher,description) VALUES ('1002','Math','Miss. Liu','the exam is difficult');

/*Insert four record into score table*/
INSERT INTO STUDENT_EXAMINATION_SYS.score(score_id,student_id,subject_id,score) VALUES ('1','001','1001',80);
INSERT INTO STUDENT_EXAMINATION_SYS.score(score_id,student_id,subject_id,score) VALUES ('2','002','1002',60);
INSERT INTO STUDENT_EXAMINATION_SYS.score(score_id,student_id,subject_id,score) VALUES ('3','001','1001',70);
INSERT INTO STUDENT_EXAMINATION_SYS.score(score_id,student_id,subject_id,score) VALUES ('4','002','1002',60.5);

